// Industry options for company/startup industry selection
export const INDUSTRIES = [
  'Technology',
  'Healthcare',
  'Finance',
  'Education',
  'E-commerce',
  'Real Estate',
  'Manufacturing',
  'Agriculture',
  'Energy',
  'Transportation',
  'Media & Entertainment',
  'Food & Beverage',
  'Fashion & Apparel',
  'Travel & Hospitality',
  'Sports & Fitness',
  'Gaming',
  'SaaS',
  'AI & Machine Learning',
  'Blockchain & Crypto',
  'Cybersecurity',
  'Marketing & Advertising',
  'HR & Recruitment',
  'Legal',
  'Consulting',
  'Non-profit',
  'Other'
];

// Domains of interest for all user types (multi-select)
export const INTEREST_DOMAINS = [
  'Technology',
  'AI & Machine Learning',
  'Blockchain',
  'Healthcare',
  'Fintech',
  'EdTech',
  'E-commerce',
  'SaaS',
  'Enterprise Software',
  'Consumer Apps',
  'Gaming',
  'Social Media',
  'Content Creation',
  'Marketing',
  'Sales',
  'Design',
  'Data Science',
  'Cybersecurity',
  'IoT',
  'Sustainability',
  'Clean Energy',
  'Real Estate',
  'Food Tech',
  'Travel Tech',
  'Logistics',
  'Manufacturing',
  'Agriculture',
  'Sports Tech',
  'Fashion Tech',
  'Music & Entertainment'
];
